[package]
name = "quote-scrape"
version = "0.1.0"
authors = ["hr567 <hr567@hr567.me>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
reqwest = "0.11.0"
scraper = "0.12.0"
tokio = { version = "1.0.2", features = [ "rt-multi-thread", "sync" ] }
url = "2.2.0"
